# Data Augmentation: Gaussian Noise

In [1]:
import numpy as np
import torch
import torchaudio
import IPython
import os

## Adding Gaussian Noise to examples

In [18]:
# IPython.display.Audio('../datasets/audioMinst/0_yweweler_13.wav', rate=8000)
# IPython.display.Audio('../datasets/audioMinst/5_theo_9.wav', rate=8000)
# IPython.display.Audio('../datasets/audioMinst/7_lucas_14.wav', rate=8000)
# IPython.display.Audio('../datasets/audioMinst/9_jackson_41.wav', rate=8000)

IPython.display.Audio('../datasets/dylanMnist/3_dylan.wav', rate=8000)

In [19]:
# signal, sr = torchaudio.load('../datasets/audioMinst/0_yweweler_13.wav')
# signal, sr = torchaudio.load('../datasets/audioMinst/5_theo_9.wav')
# signal, sr = torchaudio.load('../datasets/audioMinst/7_lucas_14.wav')
# signal, sr = torchaudio.load('../datasets/audioMinst/9_jackson_41.wav')

signal, sr = torchaudio.load('../datasets/dylanMnist/3_dylan.wav')
signal

tensor([[ 0.0005,  0.0007,  0.0005,  ..., -0.0015, -0.0010, -0.0007]])

In [20]:
# root mean square of signal
rms_signal = np.sqrt(torch.mean(signal**2))
rms_signal

tensor(0.0518)

In [22]:
# signal to noise ratio
snr = 9

In [23]:
# root mean square of noise
rms_noise = np.sqrt(rms_signal**2 / 10**(snr / 10))
rms_noise

tensor(0.0184)

In [7]:
noise = np.random.normal(0, rms_noise, signal.shape[1])
noise

array([-0.03248485,  0.00149192, -0.02627753, ..., -0.00586881,
        0.01755085, -0.00204116])

In [8]:
signal_with_noise = signal + noise
signal_with_noise = signal_with_noise.type(torch.FloatTensor)
signal_with_noise

tensor([[-0.0320,  0.0022, -0.0257,  ..., -0.0074,  0.0165, -0.0028]])

In [9]:
torchaudio.save('example_noise.wav', signal_with_noise, sr)

In [10]:
IPython.display.Audio('example_noise.wav', rate=8000)

## Adding Gaussian Noise to audioMnist

In [11]:
def add_gaussian_noise(signal, sr, snr=9):
    np.random.seed(42)
    
    rms_signal = np.sqrt(torch.mean(signal**2))
    rms_noise = np.sqrt(rms_signal**2 / 10**(snr / 10))
    
    noise = np.random.normal(0, rms_noise, signal.shape[1])
    
    signal_with_noise = signal + noise
    signal_with_noise = signal_with_noise.type(torch.FloatTensor)
    return signal_with_noise, sr

In [12]:
fns = os.listdir('../datasets/audioMinst')
fns.sort()
fns[:5]

['0_george_0.wav',
 '0_george_1.wav',
 '0_george_10.wav',
 '0_george_11.wav',
 '0_george_12.wav']

In [13]:
file_dir = '../datasets/audioMinst/'
noise_file_dir = '../datasets/audioMnistNoise/'
noise_fns = []
for fn in fns:
    split = fn.split('.')
    split[0] += '_noise'
    noise_fn = '.'.join(split)
    
    signal, sr = torchaudio.load(file_dir + fn)
    signal_with_noise, sr = add_gaussian_noise(signal, sr)
    
    torchaudio.save(noise_file_dir + noise_fn, signal_with_noise, sr)